name: Validate Docker image

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build application image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: localstack-viewer:ci
